// Tribes 2 Input Map File
moveMap.clearMap();
moveMap.bindCmd(keyboard, "escape", "", "escapeFromGame();");
moveMap.bind(keyboard, "alt e", toggleEditor);
moveMap.bind(keyboard, "pageup", pageMessageHudUp);
moveMap.bind(keyboard, "pagedown", pageMessageHudDown);
moveMap.bind(keyboard, "shift w", prevWeapon);
moveMap.bind(keyboard, "numpad1", placeMine);
moveMap.bind(keyboard, "numpad2", movebackward);
moveMap.bind(keyboard, "numpad3", useBackPack);
moveMap.bind(keyboard, "numpad4", moveleft);
moveMap.bind(keyboard, "numpad5", jump);
moveMap.bind(keyboard, "numpad6", moveright);
moveMap.bind(keyboard, "numpad8", moveforward);
moveMap.bind(keyboard, "numpad9", throwGrenade);
moveMap.bind(keyboard, "numpad0", useFirstWeaponSlot);
moveMap.bind(keyboard, "ctrl numpad0", quickPackEnergyPack);
moveMap.bind(keyboard, "ctrl numpad1", quickPackRepairPack);
moveMap.bind(keyboard, "ctrl numpad2", quickPackShieldPack);
moveMap.bind(keyboard, "ctrl numpad3", quickPackCloakPack);
moveMap.bind(keyboard, "ctrl numpad4", quickPackJammerPack);
moveMap.bind(keyboard, "ctrl numpad5", quickPackAmmoPack);
moveMap.bind(keyboard, "ctrl numpad6", quickPackSatchelCharge);
moveMap.bind(keyboard, "ctrl numpad7", quickPackDeployableStation);
moveMap.bind(keyboard, "ctrl numpad8", quickPackIndoorTurret);
moveMap.bind(keyboard, "ctrl numpad9", quickPackOutdoorTurret);
moveMap.bind(keyboard, "ctrl numpaddivide", quickPackMotionSensor);
moveMap.bind(keyboard, "ctrl *", quickPackPulse);
moveMap.bind(keyboard, "y", TeamMessageHud);
moveMap.bind(keyboard, "v", activateChatMenuHud);
moveMap.bind(keyboard, "c", toggleCommanderMap);
moveMap.bind(keyboard, "f1", toggleHelpGui);
moveMap.bind(keyboard, "f2", toggleScoreScreen);
moveMap.bind(keyboard, "f3", startRecordingDemo);
moveMap.bind(keyboard, "f4", stopRecordingDemo);
moveMap.bind(keyboard, "f6", toggleHudWaypoints);
moveMap.bind(keyboard, "f7", toggleHudMarkers);
moveMap.bind(keyboard, "f8", toggleHudCommands);
moveMap.bind(keyboard, "f9", toggleHudTargets);
moveMap.bind(keyboard, "n", toggleTaskListDlg);
moveMap.bind(keyboard, "return", fnAcceptTask);
moveMap.bind(keyboard, "backspace", fnDeclineTask);
moveMap.bind(keyboard, "shift c", fnTaskCompleted);
moveMap.bind(keyboard, "shift x", fnResetTaskList);
moveMap.bind(keyboard, "ctrl n", toggleNetDisplayHud);
moveMap.bind(keyboard, "up", toggleZoom);
moveMap.bind(keyboard, "down", setZoomFOV);
moveMap.bind(keyboard, "end", useTargetingLaser);
moveMap.bind(keyboard, "numpaddivide", nextWeapon);
moveMap.bind(keyboard, "numlock", useRepairKit);
moveMap.bind(keyboard, "i", toggleInventoryHud);
moveMap.bind(keyboard, "numpaddecimal", useSecondWeaponSlot);
moveMap.bind(keyboard, "numpadenter", useThirdWeaponSlot);
moveMap.bind(keyboard, "+", useFourthWeaponSlot);
moveMap.bind(keyboard, "minus", useFifthWeaponSlot);
moveMap.bind(keyboard, "shift left", useSixthWeaponSlot);
moveMap.bind(keyboard, "shift down", useSeventhWeaponSlot);
moveMap.bind(keyboard, "shift up", useEighthWeaponSlot);
moveMap.bind(keyboard, "shift right", useNinthWeaponSlot);
moveMap.bind(keyboard, "shift numpad0", useTenthWeaponSlot);
moveMap.bind(keyboard, "shift numpaddecimal", selectFavorite11);
moveMap.bind(keyboard, "shift numpad5", selectFavorite16);
moveMap.bind(keyboard, "shift numpad6", selectFavorite17);
moveMap.bind(keyboard, "shift numpad7", selectFavorite18);
moveMap.bind(keyboard, "shift numpad8", selectFavorite19);
moveMap.bind(keyboard, "shift numpad9", selectFavorite20);
moveMap.bind(keyboard, "left", voteNo);
moveMap.bind(keyboard, "right", voteYes);
moveMap.bind(keyboard, "t", ToggleMessageHud);
moveMap.bind(keyboard, "u", resizeChatHud);
moveMap.bind(keyboard, "]", voiceCapture);
moveMap.bind(keyboard, "backslash", toggleFirstPerson);
moveMap.bind(keyboard, "insert", throwWeapon);
moveMap.bind(keyboard, "delete", throwPack);
moveMap.bind(keyboard, "home", throwFlag);
moveMap.bind(keyboard, "k", suicide);
moveMap.bind(keyboard, "ctrl m", toggleModHud);
moveMap.bind(keyboard, "ctrl a", toggleAdminHud);
moveMap.bind(keyboard, "ctrl p", togglePracticeHud);
moveMap.bind(mouse0, "button0", mouseFire);
moveMap.bind(mouse0, "button1", mouseJet);
moveMap.bind(mouse0, "button2", toggleFreeLook);
moveMap.bind(mouse0, "xaxis", S, 0.228070, yaw);
moveMap.bind(mouse0, "yaxis", S, 0.228070, pitch);
moveMap.bind(mouse0, "zaxis", cycleWeaponAxis);
observerMap.clearMap();
observerMap.bind(keyboard, "t", moveup);
observerMap.bind(keyboard, "b", movedown);
observerMap.bind(keyboard, "space", jump);
observerMap.bind(keyboard, "f3", SD, "0.000000 0.000000", 1.000000, startRecordingDemo);
observerMap.bind(keyboard, "f4", SD, "0.000000 0.000000", 1.000000, stopRecordingDemo);
observerMap.bind(mouse0, "button0", mouseFire);
observerMap.bind(mouse0, "button1", mouseJet);
GlobalActionMap.bind(keyboard, "grave", toggleConsole);
