datablock TSShapeConstructor(BiodermHeavyDts)
{
   baseShape = "bioderm_heavy.dts";
   sequence0 = "bioderm_heavy_root.dsq root";
   sequence1 = "bioderm_heavy_forward.dsq run";
   sequence2 = "bioderm_heavy_back.dsq back";
   sequence3 = "bioderm_heavy_side.dsq side";
   sequence4 = "bioderm_heavy_lookde.dsq look";
   sequence5 = "bioderm_heavy_lookms.dsq lookms";
   sequence6 = "bioderm_heavy_head.dsq head";
   sequence7 = "bioderm_heavy_headside.dsq headside";
   sequence8 = "bioderm_heavy_jet.dsq jet";
   sequence9 = "bioderm_heavy_land.dsq land";
   sequence10 = "bioderm_heavy_fall.dsq fall";
   sequence11 = "bioderm_heavy_jump.dsq jump";
   sequence12 = "bioderm_heavy_recoilde.dsq light_recoil";
   sequence13 = "bioderm_heavy_idlePDA.dsq idlePDA";
   sequence14 = "bioderm_heavy_diehead.dsq death1";
   sequence15 = "bioderm_heavy_diechest.dsq death2";
   sequence16 = "bioderm_heavy_dieback.dsq death3";
   sequence17 = "bioderm_heavy_dieknees.dsq death4";
   sequence18 = "bioderm_heavy_diesidelft.dsq death5";
   sequence19 = "bioderm_heavy_diesidert.dsq death6";
   sequence20 = "bioderm_heavy_dieleglft.dsq death7";
   sequence21 = "bioderm_heavy_dielegrt.dsq death8";
   sequence22 = "bioderm_heavy_dieslump.dsq death9";
   sequence23 = "bioderm_heavy_dieforward.dsq death10";
   sequence24 = "bioderm_heavy_diespin.dsq death11";
   sequence25 = "bioderm_heavy_celsalute.dsq cel1";
   sequence26 = "bioderm_heavy_celyeah.dsq cel2";
   sequence27 = "bioderm_heavy_tauntbest.dsq cel3";
   sequence28 = "bioderm_heavy_celroar.dsq cel4";
   sequence29 = "bioderm_heavy_tauntbull.dsq cel5";
   sequence30 = "bioderm_heavy_celflex2.dsq cel6";
   sequence31 = "bioderm_heavy_celgora.dsq cel7";
   sequence32 = "bioderm_heavy_celjump.dsq cel8";
   sequence33 = "bioderm_heavy_ski.dsq ski";
   sequence34 = "bioderm_heavy_standjump.dsq standjump";
   sequence35 = "bioderm_heavy_looknw.dsq looknw";
};
  