// Credits list
addCreditsLine("<just:center><bitmap:cred_logo5><sbreak>");
addCreditsLine("<font:Univers:22>");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Producer/Director<spop><spop>");
addCreditsLine("Dave \"QIX\" Georgeson");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Associate Producer<spop><spop>");
addCreditsLine("Daryl \"Snow Leopard\" Nichols, Jr.");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Lead Programmer<spop><spop>");
addCreditsLine("Mark \"Got Milk?\" Frohnmayer");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Software Engineers<spop><spop>");
addCreditsLine("John \"Sne/\\ker\" Alden");
addCreditsLine("Kelly \"East\" Asay");
addCreditsLine("Shawn \"Raf\" Eastley");
addCreditsLine("Clark \"Shark\" Fagot");
addCreditsLine("John \"ÜberBob\" Folliard");
addCreditsLine("Brad \"BigDevDawg\" Heinz");
addCreditsLine("\"Missing\" Lincoln Hutton");
addCreditsLine("Greg \"Jett\" Lancaster");
addCreditsLine("Dave \"Symlink\" Moore");
addCreditsLine("Brian \"Twitch\" Ramage");
addCreditsLine("Mitch \"Skeet\" Shaw");
addCreditsLine("Tinman \"Kidney Thief\"");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Designers<spop><spop>");
addCreditsLine("Eric \"Rated z\" Lanz");
addCreditsLine("Dave \"Diamondback\" Meddish");
addCreditsLine("Jesse \"DrAwkward\" Russell");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Art Direction<spop><spop>");
addCreditsLine("Craig \"jimmy\" Maitlen");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Artists<spop><spop>");
addCreditsLine("Robert \"Pelias Maximus\" Caracol");
addCreditsLine("Ian \"ETCmodel02\" Christy ");
addCreditsLine("Jade \"FrankRizzo\" Dhabolt");
addCreditsLine("Jon \"OrphanKazrak\" Lanz");
addCreditsLine("Dave \"OldDawg\" Lauck");
addCreditsLine("Matthew \"Rickets\" Reynolds");
addCreditsLine("Paul \"Decoy\" Rheinfelder");
addCreditsLine("Thomas \"TOMIN8R\" VanVelkinburgh");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Writer<spop><spop>");
addCreditsLine("Blake \"Hexabolic\" Hutchins");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>HTML Community<spop><spop>");
addCreditsLine("Pat McCarthy");
addCreditsLine("Joe Gartska");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Director of Quality Assurance<spop><spop>");
addCreditsLine("Gary \"Koros\" Stevens");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Compatibility Lab Supervisor<spop><spop>");
addCreditsLine("Pat \"3 Legged Dingo\" Callahan");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>QA Supervisor, Core Game<spop><spop>");
addCreditsLine("Ken \"Sunshine\" Eaton");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Quality Assurance<spop><spop>");
addCreditsLine("Abhishake \"Harley\" Behl");
addCreditsLine("Angus \"Chewtoy\" Campbell");
addCreditsLine("Aaron \"Boomer1111\" Denke");
addCreditsLine("Trent \"RabidSquirrel\" Donelson");
addCreditsLine("Jonalee \"cHiLaKwEeN\" Gil");
addCreditsLine("Phil \"Philtre\" Kuhlmey");
addCreditsLine("Craig \"NEK\" Marshall");
addCreditsLine("Sean \"Baby Emu\" Meichle");
addCreditsLine("David \"Plik\" Peterson");
addCreditsLine("Robert \"Mortal Wombat\" Quattrone");
addCreditsLine("Connor \"der Todesritter\" Salisbury");
addCreditsLine("Joe \"Callahan\" Smith");
addCreditsLine("Mark \"SurferMark\" Storie");
addCreditsLine("Sue \"Othello\" Ung");
addCreditsLine("Cody \"Infirmo\" Yarbrough");
addCreditsLine("Drew \"Mongo\" Zilm");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>QA Internationalization:<spop><spop>");
addCreditsLine("Lloyd \"Tank\" Madden");
addCreditsLine("Frank \"Schnack\" Matzke");
addCreditsLine("Markus \"Beule\" Rafflenbeul");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Motion Capture Team<spop><spop>");
addCreditsLine("Technical Director: Troy McFarland");
addCreditsLine("Performer: Cosmo Hom");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Digital Video Support Team<spop><spop>");
addCreditsLine("Director: Jim\"zootboy\" Carey");
addCreditsLine("Sage \"3Dkid\" Freeman");
addCreditsLine("Steve \"opticNerve\" Bradford");
addCreditsLine("Tonya \"Agentmoody\" Stumphauzer");
addCreditsLine("Troy \"cann n fodder\" McFarland");
addCreditsLine("Kate \"reelBoss\" Alley");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Movie Intro<spop><spop>");
addCreditsLine("PBDigital, Inc.");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Installer<spop><spop>");
addCreditsLine("Chris Mahnken");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Special Thanks<spop><spop>");
addCreditsLine("Mark Brenneman");
addCreditsLine("Nels Bruckner");
addCreditsLine("Barry Drew");
addCreditsLine("Tim Gift");
addCreditsLine("Gerald Harrison");
addCreditsLine("Shannon Holder");
addCreditsLine("Jared Keller");
addCreditsLine("Ti Kwa");
addCreditsLine("Joe Maruschak");
addCreditsLine("Rick Overman");
addCreditsLine("Helen Pai");
addCreditsLine("Scott Rudi");
addCreditsLine("Shawn Sharp");
addCreditsLine("Neal Skorpen");
addCreditsLine("Weston Tracy");
addCreditsLine("Pete Walker");
addCreditsLine("Maren Wyatt");
addCreditsLine("Scott Youngblood");
addCreditsLine("");
addCreditsLine("zlib Development Team");
addCreditsLine("libPNG Development Team");

// TR2
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Team Rabbit 2<spop><spop>");
addCreditsLine("Codality, Inc.");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Codality President/Designer<spop><spop>");
addCreditsLine("Michael \"KineticPoet\" Johnston");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Codality Developers<spop><spop>");
addCreditsLine("Dan \"daunt\" Kolta");
addCreditsLine("Scott \"FSB-AO\" Estabrook");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Codality Sound Effects<spop><spop>");
addCreditsLine("John \"CObbler\" Carter");
addCreditsLine("Buddy \"sLaM\" Pritchard");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Codality 3D Artist<spop><spop>");
addCreditsLine("Gregg \"illy\" Fellows");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Codality Additional Maps<spop><spop>");
addCreditsLine("Alan \"Nefilim\" Schwertel");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Codality 2D Artist<spop><spop>");
addCreditsLine("Kenneth \"SONOFMAN\" Cook");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Codality Special Thanks<spop><spop>");
addCreditsLine("Eric \"Special\" Chu");
addCreditsLine("Jonathan \"Sojourn\" Parker");
addCreditsLine("Matt \"aerobahn\" Willis");
addCreditsLine("Taylor \"Banana Man\" Stewart");
addCreditsLine("Team 5150");
addCreditsLine("Team Euphoria");
addCreditsLine("Team Imperial Elite");
addCreditsLine("");

addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Business Unit Manager for Sierra Studios<spop><spop>");
addCreditsLine("Mark Hood");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Brand Manager<spop><spop>");
addCreditsLine("Lee Rossini");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>European Brand Manager<spop><spop>");
addCreditsLine("Djamil Kemal");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Europe/Asia Marketing Manager<spop><spop>");
addCreditsLine("Michael Fuller");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Asia Brand Manager<spop><spop>");
addCreditsLine("Deana Erickson");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Director of Marketing<spop><spop>");
addCreditsLine("Koren Buckner");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>VP of Marketing<spop><spop>");
addCreditsLine("Jim Veevaert");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Channel Promotions<spop><spop>");
addCreditsLine("Michael Whitehead");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Web Development Mgr.<spop><spop>");
addCreditsLine("Guy Welch");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Marketing Assistant<spop><spop>");
addCreditsLine("Michael Cowan");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Public Relations Mgr.<spop><spop>");
addCreditsLine("Hillary Crowley ");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Director<spop><spop>");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Creative Services<spop><spop>");
addCreditsLine("Laura Kleinhofs ");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Creative Director For<spop><spop>");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Creative Services<spop><spop>");
addCreditsLine("Brandon Walker");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Sr. Account Manager<spop><spop>");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Creative Services<spop><spop>");
addCreditsLine("Kevin Lamb");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Package Design<spop><spop>");
addCreditsLine("Moore Design Group");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Production Manager<spop><spop>");
addCreditsLine("Sheri-Lou Stannard");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Manual Layout<spop><spop>");
addCreditsLine("Kim McGovern");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Localization Coordinator<spop><spop>");
addCreditsLine("Warren Wright");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Sound Effects<spop><spop>");
addCreditsLine("EFX/Wilshire Studios");
addCreditsLine("CS Productions Inc.");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Voice Recording<spop><spop>");
addCreditsLine("Bad Animals");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Voice Processing<spop><spop>");
addCreditsLine("CS Productions Inc.");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Music<spop><spop>");
addCreditsLine("Tim Clarke and Score! Studios");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Sierra On-Line Multiplayer Services<spop><spop>");
addCreditsLine("Aaron Hunt");
addCreditsLine("Erik De Bonte");
addCreditsLine("Bill Dewey");
addCreditsLine("Colen Garoutte-Carson");
addCreditsLine("Max Klaiser");
addCreditsLine("Brent LaPoint");
addCreditsLine("Neeraj Murarka");
addCreditsLine("Mike Nicolino");
addCreditsLine("Lee Olds");
addCreditsLine("Ross Perez");
addCreditsLine("Darren Robinson");
addCreditsLine("Brian Rothstein");
addCreditsLine("Jeff Routledge");
addCreditsLine("Dean Webster");
addCreditsLine("Kelly Zmak");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Voice Talent<spop><spop>");
addCreditsLine("John Armstrong");
addCreditsLine("Mark Berry");
addCreditsLine("Kiamalise Budak");
addCreditsLine("Kymberli Colbourne");
addCreditsLine("Craig English");
addCreditsLine("Kit Harris");
addCreditsLine("Jay Hopper");
addCreditsLine("Mike Madeoy");
addCreditsLine("Dex Manley");
addCreditsLine("Kate Myre");
addCreditsLine("Matt Reidy");
addCreditsLine("Gary Schwartz");
addCreditsLine("Jen Taylor");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Linux Port<spop><spop>");
addCreditsLine("Loki Software, Inc.");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Loki President<spop><spop>");
addCreditsLine("Scott \"Highlander\" Draeker");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Linux Installer<spop><spop>");
addCreditsLine("Stephane \"Megastep\" Peter");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Linux Programming<spop><spop>");
addCreditsLine("Michael \"Briareos\" Vance");
addCreditsLine("Joe \"TsaoTsao\" Valenzuela");
addCreditsLine("Sam \"Hercules\" Lantinga");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Linux Q/A and Support<spop><spop>");
addCreditsLine("Andy \"Yoda\" Mecham");
addCreditsLine("Mike \"Heimdall\" Phillips");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Linux Manual<spop><spop>");
addCreditsLine("Kayt \"Sigyn\" Sorhaindo");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Loki Artwork<spop><spop>");
addCreditsLine("Jason \"Pais\" Kim");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Loki System Support<spop><spop>");
addCreditsLine("Rafael \"Raistlin\" Barrero");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Loki Business Manager<spop><spop>");
addCreditsLine("Yvonne \"YDS\" De Sollar");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Loki Customer Support<spop><spop>");
addCreditsLine("Brandon \"Particle\" Carter");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Loki Beta Testers<spop><spop>");
addCreditsLine("James \"idcmp\" Atwill");
addCreditsLine("Brandon \"bbeattie\" Beattie");
addCreditsLine("Fionn Behrens");
addCreditsLine("Jonathan \"Suraklyn\" Bowser");
addCreditsLine("Patrick \"Phineas\" Calhoun");
addCreditsLine("Wayne \"ttol\" Chang");
addCreditsLine("Nash \"twostar\" Clemens");
addCreditsLine("Mike \"madcat\" Delaney");
addCreditsLine("Matthew \"DivineHawk\" Eaton");
addCreditsLine("Rodney \"meff\" Gordon II");
addCreditsLine("Pavan \"Phantom\" Gupta");
addCreditsLine("Christopher \"Malkier\" Hahn");
addCreditsLine("John \"OverCode\" Hall");
addCreditsLine("Jesse \"Abysmal\" Hanna");
addCreditsLine("Steven \"Ashari\" Hatfield");
addCreditsLine("David \"NeoTron\" Hedbor");
addCreditsLine("Matt \"malloc_master\" Helsley");
addCreditsLine("Simon \"red_one\" Hill");
addCreditsLine("Gareth \"3D-Guru\" Hughes");
addCreditsLine("Zephaniah E. Hull");
addCreditsLine("Guy \"Guido\" Hutchison");
addCreditsLine("Joshua Kleiner");
addCreditsLine("Geoff \"Rambo\" Lewis");
addCreditsLine("Jason \"Deadman\" Lundy");
addCreditsLine("Gregory \"Centove\" McLean");
addCreditsLine("Patrick \"WormBoy\" McNeill");
addCreditsLine("Jeff \"Judecca\" Mrochuk");
addCreditsLine("Patrick \"linuxpunkr...\" Mullen");
addCreditsLine("Prof. Dr. Nao");
addCreditsLine("Jody \"Dweebs\" Newell");
addCreditsLine("Bob \"Shapecharge\" O'Brien");
addCreditsLine("Kyle \"JebusSaveMe\" Olsen");
addCreditsLine("John \"joe\" Osborne");
addCreditsLine("Chris \"Super-K\" Osgood");
addCreditsLine("Jon \"Railroad\" Revie");
addCreditsLine("Michael \"M00k3y\" Ritner");
addCreditsLine("Aron \"Govt.Cheese\" Rosenberg");
addCreditsLine("Yuri \"Mystro\" Sagalov");
addCreditsLine("Marinus \"foser\" Schraal");
addCreditsLine("SKILL5");
addCreditsLine("Ryan Stotts");
addCreditsLine("Dan \"XFree86\" Temple");
addCreditsLine("Terry \"keerf\" Warner");
addCreditsLine("Chris \"UmytBnxt\" Watkins");
addCreditsLine("Michael \"themime\" Whitten");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>GLSetup Team<spop><spop>");
addCreditsLine("Chris Hecker");
addCreditsLine("Rob Felter");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("<spush><color:BDBE9C>Thanks to all the wives, girlfriends and children of the hardworking Dev Team members. Your patience and sacrifice has allowed us to complete a project of which we are all tremendously proud.  None of it would have been possible without you.<spop>");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Meta Testers<spop><spop>");
addCreditsLine("Alex Flagg");
addCreditsLine("Alex \"LogRoller\" Ogilvie");
addCreditsLine("Adam Mitter");
addCreditsLine("Alan \"Otter\" Ragg");
addCreditsLine("Alex \"SaGe\" Chappuis");
addCreditsLine("Alexandre \"[cF]Alex\" Clerc-Gagnoux");
addCreditsLine("Allen \"TheRedDread\" Drennan");
addCreditsLine("Andreas Jalsovec");
addCreditsLine("Anton Wiegert");
addCreditsLine("Arden H. \"TF Pookie\" Nguyen");
addCreditsLine("Bart \"=DB=Seven\" Smith");
addCreditsLine("Ben \"Diox\" May");
addCreditsLine("Ben \"Hypn0tik\" Tamler");
addCreditsLine("Ben \"Stan\" Gray");
addCreditsLine("Bobby \"Mogart\" Rider");
addCreditsLine("Bodhi \"Heliometus Max\" Daher");
addCreditsLine("Brad \"Bort\" Klann");
addCreditsLine("Bret D. \"Bacchus\" Wilson");
addCreditsLine("Brian \"Aftershock\" Parker");
addCreditsLine("Carl \"Daddy\" Anderson");
addCreditsLine("Charlie Schillberg");
addCreditsLine("Chason \"Phantom Stranger\" Ellis");
addCreditsLine("Chris \"Pie4Foo\" Abele");
addCreditsLine("Chris \"Tythan\" Caviness");
addCreditsLine("Chris \"Fubar\" Duncan");
addCreditsLine("Christian \"S3 Crucifix\" Peth");
addCreditsLine("Colin \"Dark Wraith\" Howitt");
addCreditsLine("Cory \"Omega Man\" Altheide");
addCreditsLine("\"Cowboy\" Ben Alman");
addCreditsLine("Crystal McHale");
addCreditsLine("Dan \"Avatar\" Lyons");
addCreditsLine("Daniel \"|5150|Keyser\" Gallegos");
addCreditsLine("Daniel \"Emp\" Arnold");
addCreditsLine("Daniel \"Snaggs\" Soderstrom");
addCreditsLine("Daniel \"Trebz\" Nolan");
addCreditsLine("Daniel \"Wizard_TPG\" Neilsen");
addCreditsLine("Daniel \"Shadow Mage\" Nichols");
addCreditsLine("Daniel \"Spooger\" Patton");
addCreditsLine("Danny \"OmegaRed\" Cotton");
addCreditsLine("Darion \"Shadower\" Lowenstein");
addCreditsLine("Darren \"Fidelio\" Mitchell");
addCreditsLine("Dave \"Tycho\" Fried");
addCreditsLine("David \"DOX\" Oxwell");
addCreditsLine("David \"Killdawg\" DeBoer");
addCreditsLine("David MacIntosh");
addCreditsLine("Dean \"VolcoM\" Sykes");
addCreditsLine("Dean Tate");
addCreditsLine("Dennis \"Chickenboo\" Fox");
addCreditsLine("Erik \"Mustard\" de Jong");
addCreditsLine("Gabor \"Dezso a HUN\" Orban");
addCreditsLine("Gabriel \"Warwitch\" David");
addCreditsLine("Gavin \"Suds\" Henrick");
addCreditsLine("Gino \"tAngGSI\" Gard");
addCreditsLine("Glenn \"IcyHot\" Wisbey");
addCreditsLine("Gregory \"Brak Panda\" Pesochin");
addCreditsLine("Gregory \"Strife\" Hill");
addCreditsLine("Hannes \"Cohen\" Wagner");
addCreditsLine("Ian \"Kowboy\" Gonsalves");
addCreditsLine("Ian Threadgold");
addCreditsLine("J Alex \"Blackheart\" Wheeler");
addCreditsLine("James \"Warbird\" Gentry III");
addCreditsLine("James C. \"Lothos\" Hanna");
addCreditsLine("Jason \"Circuit\" Jenkins");
addCreditsLine("Jason \"Iron Chef\" Goodowens");
addCreditsLine("Jason \"Lumberjack\" De Arte");
addCreditsLine("Jeff \"Hellsfury\" Shaw");
addCreditsLine("Jeremy \"Xevious\" Burke");
addCreditsLine("Jerry \"Tycho Brahe\" Holkins");
addCreditsLine("Joe \"Quadrature\" Downs");
addCreditsLine("Joe Bell Grant");
addCreditsLine("Joern \"Pangur\" Schnautz");
addCreditsLine("John \"Dr.Jones\" Burnett");
addCreditsLine("Jon \"Ratorasniki\" Naiman");
addCreditsLine("Jonathan \"Chaser\" Bale");
addCreditsLine("Joost \"jschuur\" Schuur");
addCreditsLine("Josh \"Red Sirus\" Hoey");
addCreditsLine("Kevin \"Rifter\" Rank");
addCreditsLine("Kevin \"Kevlar\" Middleton");
addCreditsLine("Kyle \"{DP}AzN^DoG\" Godfrey");
addCreditsLine("Kyle \"Wiggy\" Bennett");
addCreditsLine("Laura \"Dolph Lundgren\" Schreiner");
addCreditsLine("Lorne \"Writer\" Laliberte");
addCreditsLine("Mac \"McNaughton\" Miller");
addCreditsLine("Mario \"Lone Gunman\" Batlle");
addCreditsLine("Mark \"Ferret-of-Death\" Siciliano");
addCreditsLine("Mark \"Old Skul\" Szabo");
addCreditsLine("Mark \"Panama Jack\" Dickenson");
addCreditsLine("Markus Rafflenbeul");
addCreditsLine("Mat Bettinson");
addCreditsLine("Matt \"{SiR}SoulJAH\" Culp");
addCreditsLine("Matt \"Colosus\" DeWald");
addCreditsLine("Matt Sobotka");
addCreditsLine("Matthew \"4u2c\" McKeown");
addCreditsLine("Mattijs \"3bird\" Jonker");
addCreditsLine("Michael \"Optimizer\" Hamlett");
addCreditsLine("Michael \"Rave\" Mogill");
addCreditsLine("Michael A Nance");
addCreditsLine("Michael James \"Tenabrae\" Edwards");
addCreditsLine("Mike \"Ragman\" Hillebrecht");
addCreditsLine("Mike \"Gabriel\" Krahulik");
addCreditsLine("Mike \"Gangreen\" Burton");
addCreditsLine("Moussa Khan");
addCreditsLine("N. David \"MlakMavet\" Griffin");
addCreditsLine("Nathan \"[HvC]NaTeDoGG\" Sweet");
addCreditsLine("Nick \"Enhanced Panda\" Orlich");
addCreditsLine("Nick \"Leb\" Petska");
addCreditsLine("Nick S. \"Enlightened One\" Pasto");
addCreditsLine("Nikita \"FSB-SPY\" Bogolyubov");
addCreditsLine("Olivier \"[cf] OroX\" Roulx");
addCreditsLine("Omar Yehia");
addCreditsLine("Pamela A. \"Diva\" Holmberg");
addCreditsLine("Paul \"RuinatioN\" Wright");
addCreditsLine("Paul \"Teknoice\" Morris");
addCreditsLine("Penny \"Killer Girl\" Miller");
addCreditsLine("Peter \"dev\" Kazmierow");
addCreditsLine("Ric \"Dr Chmod\" Moseley");
addCreditsLine("\"NoFix\"");
addCreditsLine("Rob \"Coyote\" Duffy");
addCreditsLine("Robert Huebner");
addCreditsLine("Rod Chrenek");
addCreditsLine("Ron Oliver II");
addCreditsLine("Ross \"Bytor\" Carlson");
addCreditsLine("Roy \"Cannonfodder\" Greenhalgh");
addCreditsLine("Ryan \"Kelster\" Kelly");
addCreditsLine("Ryan \"Onyxwulf\" Gilfillan");
addCreditsLine("Ryan \"StoneWolf\" Thernes");
addCreditsLine("Scott \"Smedly\" Medlin");
addCreditsLine("Sean \"Pubknight\" Bryson ");
addCreditsLine("Sebastien \"[cF]PreD\" Guillemet");
addCreditsLine("Shane \"Mental Trousers\" Taylor");
addCreditsLine("Shane \"Santa\" Beaumont");
addCreditsLine("Shane \"Shaneman\" Evans");
addCreditsLine("Stefan Grufman");
addCreditsLine("Stefan \"Skace\" Kiehne");
addCreditsLine("Stephen \"Cato\" Farquhar");
addCreditsLine("Stephen \"SL83\" Limowski");
addCreditsLine("Steve \"Presto\" Eisner");
addCreditsLine("Taylor \"Emo1313\" Suchan");
addCreditsLine("Thomas \"Mantis\" Kumpik, Jr.");
addCreditsLine("Tim \"Zear\" Hammock");
addCreditsLine("Todd \"Fuzzy Lumpkins\" Sjoblom");
addCreditsLine("Tom \"Falcon\" Vogt");
addCreditsLine("Tyler \"Raskal\" Jacobson");
addCreditsLine("Tyler \"Sty\" Frans");
addCreditsLine("Tyler Wilson");
addCreditsLine("Werner Poetzelberger");
addCreditsLine("Willem \"Talita\" Bison");
addCreditsLine("William \"Altaic\" Knop");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Beta Testers<spop><spop>");
addCreditsLine("Aaron Brown");
addCreditsLine("Aaron Butler");
addCreditsLine("Aaron Reed");
addCreditsLine("Aaron Scott Reed");
addCreditsLine("Aaron Semeniuk");
addCreditsLine("Aaron Wisner");
addCreditsLine("Aaron Younger");
addCreditsLine("Adam B. Argo");
addCreditsLine("Adam Becker");
addCreditsLine("Adam Corvin");
addCreditsLine("Adam England");
addCreditsLine("Adam King");
addCreditsLine("Adam Kleifield ");
addCreditsLine("Adam McCreight");
addCreditsLine("Adam Mitter");
addCreditsLine("Adam S. Pedersen");
addCreditsLine("Adam Toering");
addCreditsLine("Adam Williams");
addCreditsLine("Adrian Telfer");
addCreditsLine("Akihiro Inoue");
addCreditsLine("Al Harrington");
addCreditsLine("Alan Peng");
addCreditsLine("Alan Ragg");
addCreditsLine("Alayton Norgard");
addCreditsLine("Alberto Petrozzi");
addCreditsLine("Alden Tan");
addCreditsLine("Alex Chappuis");
addCreditsLine("Alex Flagg");
addCreditsLine("Alex Gourley");
addCreditsLine("Alex Jakes JR");
addCreditsLine("Alex Jeng");
addCreditsLine("Alex Ogilvie");
addCreditsLine("Alex Porter");
addCreditsLine("Alex Taylor");
addCreditsLine("Alex Zanfir");
addCreditsLine("Alexander Baldoria");
addCreditsLine("Alexander Flagg");
addCreditsLine("Alexander Marschal");
addCreditsLine("Alexander van Rijn");
addCreditsLine("Alexandr Koshelev");
addCreditsLine("Alexandre Clerc-Gagnoux");
addCreditsLine("Alexandre Pomi");
addCreditsLine("Alexandre Ramos");
addCreditsLine("Alexei Sapsford");
addCreditsLine("Allen Drennan");
addCreditsLine("Allen Grusecki");
addCreditsLine("Amir Assali");
addCreditsLine("Amir Grad");
addCreditsLine("Anatoly Ropotov");
addCreditsLine("Andre Koch");
addCreditsLine("Andrea Primadei");
addCreditsLine("Andreas Leondidis");
addCreditsLine("Andrew Baum");
addCreditsLine("Andrew Fort");
addCreditsLine("Andrew Price");
addCreditsLine("Andrew Stockman");
addCreditsLine("Andy Chong");
addCreditsLine("Andy Swanson");
addCreditsLine("Angus Campbell");
addCreditsLine("Anthony Bermudez");
addCreditsLine("Anthony Mills");
addCreditsLine("Antonio Ferrari");
addCreditsLine("Antti Hätinen");
addCreditsLine("Arden H Nguyen");
addCreditsLine("Arthur Troncoso");
addCreditsLine("Ata Yavalar");
addCreditsLine("Attila Fur");
addCreditsLine("Audie Martin");
addCreditsLine("Barbara J. Webb");
addCreditsLine("Baret Julien");
addCreditsLine("Baron Wolt");
addCreditsLine("Bart Haesaerts");
addCreditsLine("Bart Maegh");
addCreditsLine("Bart Peiren");
addCreditsLine("Bart Smith");
addCreditsLine("Bart Waeterschoot");
addCreditsLine("Beau Hale");
addCreditsLine("Ben Anderson");
addCreditsLine("Ben Cantwell");
addCreditsLine("Ben Cuthbert");
addCreditsLine("Ben De Decker");
addCreditsLine("Ben Dobbs");
addCreditsLine("Ben Floren");
addCreditsLine("Ben Gray");
addCreditsLine("Ben Lawton");
addCreditsLine("Ben Martel");
addCreditsLine("Ben May");
addCreditsLine("Ben Pierson");
addCreditsLine("Ben Stone");
addCreditsLine("Ben Tamler");
addCreditsLine("Benjamin Alman");
addCreditsLine("Benjamin Denholm");
addCreditsLine("Benjamin Luck");
addCreditsLine("Benoît Dewaele");
addCreditsLine("Bernd Berheide");
addCreditsLine("Bernhard Seiser");
addCreditsLine("Bill Eccleston");
addCreditsLine("Bill Lewis");
addCreditsLine("Bill Rodenbaugh");
addCreditsLine("Bjorn Sleypen");
addCreditsLine("Bo McCoy");
addCreditsLine("Bodhi Daher");
addCreditsLine("Boris Stock");
addCreditsLine("Brad Butcher");
addCreditsLine("Brad Conner");
addCreditsLine("Brad DeLong");
addCreditsLine("Brad Goehring");
addCreditsLine("Brad Herman");
addCreditsLine("Brad Klann");
addCreditsLine("Bram Noëz");
addCreditsLine("Brandon Cantrell");
addCreditsLine("Brandon Knez");
addCreditsLine("Brandon W. Easley");
addCreditsLine("Brandy Straatman");
addCreditsLine("Bret D. Wilson");
addCreditsLine("Brett Carlson");
addCreditsLine("Bri Pas");
addCreditsLine("Brian Barnes");
addCreditsLine("Brian Charles Moses");
addCreditsLine("Brian Helms");
addCreditsLine("Brian Hon");
addCreditsLine("Brian Lorey");
addCreditsLine("Brian Mercer");
addCreditsLine("Brian Nakash");
addCreditsLine("Brian Parker");
addCreditsLine("Brian Vitale");
addCreditsLine("Brian Walsh");
addCreditsLine("Brian Weberling");
addCreditsLine("Brian Wright");
addCreditsLine("Brice Gharst");
addCreditsLine("Brion Miller");
addCreditsLine("Bruce Oberleitner");
addCreditsLine("Bryan Heard");
addCreditsLine("Bryan Stroop");
addCreditsLine("Buddy Pritchard");
addCreditsLine("C. Henrique Olifiers");
addCreditsLine("C. Kyle Bennett");
addCreditsLine("C.D. Thurman");
addCreditsLine("Caleb Cauthon");
addCreditsLine("Camere Danilo");
addCreditsLine("Camille Castel");
addCreditsLine("Carl Anderson");
addCreditsLine("Carl Andersson");
addCreditsLine("Carl Buckley");
addCreditsLine("Carl Chambers");
addCreditsLine("Carla Louisa Andrews");
addCreditsLine("Carlos Delgado");
addCreditsLine("Carolyn Manis");
addCreditsLine("Casey O'Connor");
addCreditsLine("Casper Lund");
addCreditsLine("Cedric Hourcade");
addCreditsLine("Chad Jolly");
addCreditsLine("Channon Wong");
addCreditsLine("Charl Theron");
addCreditsLine("Charles Cresswell");
addCreditsLine("Charles F. Gast");
addCreditsLine("Charles Koelemay");
addCreditsLine("Charlie VanDyke");
addCreditsLine("Chason Ellis");
addCreditsLine("Choi Byeong-Ho");
addCreditsLine("Chow Yun");
addCreditsLine("Chris Abele");
addCreditsLine("Chris Aster");
addCreditsLine("Chris Becton");
addCreditsLine("Chris Boucher");
addCreditsLine("Chris Boyd");
addCreditsLine("Chris Browning");
addCreditsLine("Chris Buckler");
addCreditsLine("Chris Cacioppo");
addCreditsLine("Chris Calande");
addCreditsLine("Chris Cauthen");
addCreditsLine("Chris Caviness");
addCreditsLine("Chris Cullen");
addCreditsLine("Chris Dettmann");
addCreditsLine("Chris Duncan");
addCreditsLine("Chris Farmer");
addCreditsLine("Chris Fields");
addCreditsLine("Chris Frederick");
addCreditsLine("Chris Hersey");
addCreditsLine("Chris Hewitt");
addCreditsLine("Chris Holfeld");
addCreditsLine("Chris Houston");
addCreditsLine("Chris Jones");
addCreditsLine("Chris Joyce");
addCreditsLine("Chris Kissinger");
addCreditsLine("Chris Mahnken");
addCreditsLine("Chris Mermagen");
addCreditsLine("Chris Walker");
addCreditsLine("Chris Weatherwax");
addCreditsLine("Chris Weeks");
addCreditsLine("Chris Willis");
addCreditsLine("Chris Wilson");
addCreditsLine("Chris Youren");
addCreditsLine("Christian D. Loftus");
addCreditsLine("Christian Davis");
addCreditsLine("Christian Peth");
addCreditsLine("Christoher Rex Prangnell");
addCreditsLine("Christoph Hagenbrock");
addCreditsLine("Christoph Schwayer");
addCreditsLine("Christopher Clarke");
addCreditsLine("Christopher Donahue");
addCreditsLine("Christopher Duffield");
addCreditsLine("Christopher Forbes Davidson");
addCreditsLine("Christopher Gray");
addCreditsLine("Christopher J. Burden");
addCreditsLine("Christopher Jones");
addCreditsLine("Christopher Tan");
addCreditsLine("Chuang Li-chung");
addCreditsLine("Chuck Houlette");
addCreditsLine("Chum Chancharadeth");
addCreditsLine("Clarence Jones");
addCreditsLine("Clark Bradley");
addCreditsLine("Clay Reyer");
addCreditsLine("Clay Taylor");
addCreditsLine("Clayton Griffin");
addCreditsLine("Cliff Yaun");
addCreditsLine("Clint Gallon");
addCreditsLine("Cody Edwards");
addCreditsLine("Colin Howitt");
addCreditsLine("Colin Korbelas");
addCreditsLine("Colin Laughlin");
addCreditsLine("Colin murray");
addCreditsLine("Collin Theseira");
addCreditsLine("Cory Altheide");
addCreditsLine("Cory Hill");
addCreditsLine("Cory Miller");
addCreditsLine("Craig Beers");
addCreditsLine("Craig Paterson");
addCreditsLine("Crystal McHale");
addCreditsLine("Curtis Campbell");
addCreditsLine("Curtis Rock");
addCreditsLine("Daire Garvey");
addCreditsLine("Dallas Harris");
addCreditsLine("Damien Webber");
addCreditsLine("Damien Webber");
addCreditsLine("Dan Ilan");
addCreditsLine("Dan Kolta");
addCreditsLine("Dan Lyons");
addCreditsLine("Dan Peters");
addCreditsLine("Dan Schmierer");
addCreditsLine("Dan Sego");
addCreditsLine("Dane Barber");
addCreditsLine("Daniel Chenoweth");
addCreditsLine("Daniel Costantini");
addCreditsLine("Daniel Gallegos");
addCreditsLine("Daniel J. Patton");
addCreditsLine("Daniel Medini");
addCreditsLine("Daniel Neilsen");
addCreditsLine("Daniel Nolan");
addCreditsLine("Daniel Palmer");
addCreditsLine("Daniel Smith");
addCreditsLine("Daniel Soderstrom");
addCreditsLine("Danny Cotton");
addCreditsLine("Danny Van Bronkhorst");
addCreditsLine("Darion Lowenstein");
addCreditsLine("Darko Miodrag");
addCreditsLine("Darragh O' Toole");
addCreditsLine("Darren Asato");
addCreditsLine("Darren Menzies");
addCreditsLine("Darren Mitchell");
addCreditsLine("Darren Sorrell");
addCreditsLine("Darren Tabor");
addCreditsLine("Dave Benedict");
addCreditsLine("Dave Calame");
addCreditsLine("Dave Fried");
addCreditsLine("Dave Schwinger");
addCreditsLine("Dave Warner");
addCreditsLine("Dave Wight");
addCreditsLine("David Bonds");
addCreditsLine("David Chubb");
addCreditsLine("David De Boer");
addCreditsLine("David Higgins");
addCreditsLine("David Lindberg");
addCreditsLine("David Liu");
addCreditsLine("David Oxwell");
addCreditsLine("David Paukstys");
addCreditsLine("David Peterson");
addCreditsLine("David Quinn");
addCreditsLine("David Richards");
addCreditsLine("David Stetz");
addCreditsLine("David W. Atchley");
addCreditsLine("Dean Sykes");
addCreditsLine("Deffi");
addCreditsLine("Denish Puspparajah");
addCreditsLine("Dennis Fox");
addCreditsLine("Dennis Goedbloed");
addCreditsLine("Dennis Gurock");
addCreditsLine("Dennis Oden");
addCreditsLine("Dennis Price");
addCreditsLine("Dennis vd Broek");
addCreditsLine("Derek Bao");
addCreditsLine("Derek McGee");
addCreditsLine("Derek Millar");
addCreditsLine("Derek Mulder");
addCreditsLine("Derrick T. Woolworth");
addCreditsLine("Devin Blair");
addCreditsLine("Devin C. Glenn");
addCreditsLine("Devin L. Ganger");
addCreditsLine("Dimitri Gunsing");
addCreditsLine("Dion Clapperton");
addCreditsLine("Dirk Lambert");
addCreditsLine("Dirk Moerenhout");
addCreditsLine("Dominic Carus");
addCreditsLine("Donald Ho");
addCreditsLine("Donald Mills");
addCreditsLine("Duncan Law");
addCreditsLine("Duncan McLeod");
addCreditsLine("Dustin Lesan");
addCreditsLine("Dustin Miller");
addCreditsLine("Dyanne Lee");
addCreditsLine("Ed Molnar");
addCreditsLine("Ed Sin");
addCreditsLine("Eddie Manso");
addCreditsLine("Eddie Pierce");
addCreditsLine("Editorial GameSurf");
addCreditsLine("Edric Borja");
addCreditsLine("Eduardo Amaro");
addCreditsLine("Edward Van Brunt");
addCreditsLine("Elliot Naiman");
addCreditsLine("Emanuele");
addCreditsLine("Emiliano Saurin");
addCreditsLine("Ephraim Brodsky");
addCreditsLine("Erbil Salihoglu");
addCreditsLine("Eric Bultman");
addCreditsLine("Eric Hudzikiewicz");
addCreditsLine("Eric Iovan");
addCreditsLine("Eric Manko");
addCreditsLine("Eric Ray");
addCreditsLine("Eric Ross");
addCreditsLine("Eric Soulvie");
addCreditsLine("Eric Stankelis");
addCreditsLine("Eric Takamoto");
addCreditsLine("Eric Toledo");
addCreditsLine("Erick Apeles");
addCreditsLine("Erik de Jong");
addCreditsLine("Erik Gulbrandsen");
addCreditsLine("Ernie Page");
addCreditsLine("Erwin Esener");
addCreditsLine("Espen Andresen");
addCreditsLine("Eugene Goh");
addCreditsLine("Everett Whiteway");
addCreditsLine("Fabian Ianigro");
addCreditsLine("Faizaan Ghauri");
addCreditsLine("Fiona Stevens");
addCreditsLine("Francesco Sorrentino");
addCreditsLine("Francis To");
addCreditsLine("Frank Canedy");
addCreditsLine("Frank Collins");
addCreditsLine("Frank Hop");
addCreditsLine("Frank McGee");
addCreditsLine("Franz Töfferl");
addCreditsLine("Fred Cheng");
addCreditsLine("Fred Hill");
addCreditsLine("Frederik Kruse Hannibal");
addCreditsLine("Fulvio Tagliento");
addCreditsLine("Gabe Othman");
addCreditsLine("Gabor Orban");
addCreditsLine("Gabriel David");
addCreditsLine("Gary Caine");
addCreditsLine("Gary J. Talley");
addCreditsLine("Gary McWilliams");
addCreditsLine("Gary Milante");
addCreditsLine("Gary Schweisthal");
addCreditsLine("Gavin Henrick");
addCreditsLine("Geoff Dodd");
addCreditsLine("Geoffrey Forman");
addCreditsLine("George Campbell");
addCreditsLine("George Ganas");
addCreditsLine("George Wingard");
addCreditsLine("Gilberto Barbicinti");
addCreditsLine("Gino Gard");
addCreditsLine("Glenn Reasor");
addCreditsLine("Glenn Wisbey");
addCreditsLine("Gordon Lee");
addCreditsLine("Gordon Mak");
addCreditsLine("Gordon Wilcox");
addCreditsLine("Goty Liu");
addCreditsLine("Greg Barnett");
addCreditsLine("Greg Gilleland");
addCreditsLine("Greg Habetler");
addCreditsLine("Greg Milton");
addCreditsLine("Greg Romaszka");
addCreditsLine("Greg Walk");
addCreditsLine("Gregory Hill");
addCreditsLine("Gregory Peng");
addCreditsLine("Gregory Pesochin");
addCreditsLine("Greigg Stein");
addCreditsLine("Guillaume Neron");
addCreditsLine("Gunnar Schumann");
addCreditsLine("Guy Mirisciotta");
addCreditsLine("H.Yamao");
addCreditsLine("Hamed Khoojinian");
addCreditsLine("Hannes Wagner");
addCreditsLine("Hans David Lemons");
addCreditsLine("Harold Brown");
addCreditsLine("Harry Glaser");
addCreditsLine("Harry Kambouropoulos");
addCreditsLine("Hashish HasnaIn");
addCreditsLine("Heath Fischer");
addCreditsLine("Helge Nesøen");
addCreditsLine("Hendrik Bauer");
addCreditsLine("Hendrik Strobel");
addCreditsLine("Henk Schaefer");
addCreditsLine("Henry Lee");
addCreditsLine("Henry Martins");
addCreditsLine("Hugh Norton-Smith");
addCreditsLine("Hugh Spencer");
addCreditsLine("Hunter Luisi");
addCreditsLine("Ian Glenn");
addCreditsLine("Ian Redden");
addCreditsLine("Ian Threadgold");
addCreditsLine("Igor Bachinsky");
addCreditsLine("Issac Rosser");
addCreditsLine("Iwan Khouw");
addCreditsLine("J. Scott Randall");
addCreditsLine("Jaap de Heer");
addCreditsLine("Jack Mamais");
addCreditsLine("Jaesson Yeo");
addCreditsLine("James Balough");
addCreditsLine("James Batty");
addCreditsLine("James C. Hanna");
addCreditsLine("James Ell");
addCreditsLine("James Gentry III");
addCreditsLine("James Logan");
addCreditsLine("James Molson");
addCreditsLine("James Ramsey");
addCreditsLine("James Tucker");
addCreditsLine("James Weisgerber");
addCreditsLine("Jamie Reep");
addCreditsLine("Jan Siarov");
addCreditsLine("Jani Sundstrom");
addCreditsLine("Janne Puonti");
addCreditsLine("Jared Black");
addCreditsLine("Jared Keller");
addCreditsLine("Jarle Hauglum");
addCreditsLine("Jason Alday");
addCreditsLine("Jason Alombro");
addCreditsLine("Jason Bergman");
addCreditsLine("Jason Cross");
addCreditsLine("Jason De Arte");
addCreditsLine("Jason Fleming");
addCreditsLine("Jason Gill");
addCreditsLine("Jason Goodfellow");
addCreditsLine("Jason Goodowens");
addCreditsLine("Jason Jenkins");
addCreditsLine("Jason Kinnear");
addCreditsLine("Jason Kochan");
addCreditsLine("Jason Newington");
addCreditsLine("Jason Robert Nelson");
addCreditsLine("Jason Widy");
addCreditsLine("Javier Jiménez");
addCreditsLine("Jay Johnson");
addCreditsLine("Jay Weitekamp");
addCreditsLine("Jeff Buckland");
addCreditsLine("Jeff Chang");
addCreditsLine("Jeff Day");
addCreditsLine("Jeff Dotson");
addCreditsLine("Jeff Drouet");
addCreditsLine("Jeff Greth");
addCreditsLine("Jeff Hedges");
addCreditsLine("Jeff Lofgren");
addCreditsLine("Jeff Shauger");
addCreditsLine("Jeff Shaw");
addCreditsLine("Jeff Streeter");
addCreditsLine("Jeff Tom");
addCreditsLine("Jeffrey A. Tindle");
addCreditsLine("Jeffrey Rudolph");
addCreditsLine("Jelle Twerda");
addCreditsLine("Jens Larsson");
addCreditsLine("Jeppe Christensen");
addCreditsLine("Jeremy Burke");
addCreditsLine("Jeremy Chookas");
addCreditsLine("Jeremy Klemm");
addCreditsLine("Jeremy Rogers");
addCreditsLine("Jeremy Werkheiser");
addCreditsLine("Jeroen Rasschaert");
addCreditsLine("Jerry Annin");
addCreditsLine("Jerry Holkins");
addCreditsLine("Jerry Qassar");
addCreditsLine("Jesse Maher");
addCreditsLine("Jesse Smith");
addCreditsLine("Jim Andrews");
addCreditsLine("Jim Dale");
addCreditsLine("Jim Gosney");
addCreditsLine("Jim Richardson");
addCreditsLine("Jimmy Chandler");
addCreditsLine("Jimmy van der Have");
addCreditsLine("Joe Diamond");
addCreditsLine("Joe Dopp");
addCreditsLine("Joe Downs");
addCreditsLine("Joe Falcomata");
addCreditsLine("Joe Kennedy");
addCreditsLine("Joe Mauga");
addCreditsLine("Joe McGuire");
addCreditsLine("Joe Prowell");
addCreditsLine("Joe Seifert");
addCreditsLine("Joel Bruick");
addCreditsLine("Joern Schnautz");
addCreditsLine("Joey Snailham");
addCreditsLine("Johan Köhne");
addCreditsLine("John Bialick");
addCreditsLine("John Buckingham");
addCreditsLine("John Burnett");
addCreditsLine("John Cain");
addCreditsLine("John Colin Hanna");
addCreditsLine("John Davis");
addCreditsLine("John DeBruyn");
addCreditsLine("John Dodds");
addCreditsLine("John Finér");
addCreditsLine("John Hazelden");
addCreditsLine("John Hemaloto");
addCreditsLine("John K. Ogi");
addCreditsLine("John Kilmartin");
addCreditsLine("John Kok Chung Yoong");
addCreditsLine("John Mattison");
addCreditsLine("John Nielsen");
addCreditsLine("John Reque");
addCreditsLine("John Rodriguez");
addCreditsLine("John Tackman");
addCreditsLine("John Titus");
addCreditsLine("John Wolf");
addCreditsLine("Johnny Christensen");
addCreditsLine("Jon Callirgos");
addCreditsLine("Jon Naiman");
addCreditsLine("Jon Norris");
addCreditsLine("Jon Pudge");
addCreditsLine("Jon Simon");
addCreditsLine("Jonas Hansen");
addCreditsLine("Jonathan Bale");
addCreditsLine("Jonathan Fingas");
addCreditsLine("Jonathan Hill");
addCreditsLine("Jonathan Hilmer");
addCreditsLine("Jonathan Parker");
addCreditsLine("Jonathan Peters");
addCreditsLine("Jonathan Reed");
addCreditsLine("Jonathan Slark");
addCreditsLine("Jonathan W. Hebert");
addCreditsLine("Jonathan Whitehouse");
addCreditsLine("Jone Kajan");
addCreditsLine("Jordan Cheetin");
addCreditsLine("Jordan Mercier");
addCreditsLine("Joscha Dzielak");
addCreditsLine("Jose Magana");
addCreditsLine("Josef Jahn");
addCreditsLine("Joseph Downs");
addCreditsLine("Joseph Liu");
addCreditsLine("Joseph Walling");
addCreditsLine("Josh Hoey");
addCreditsLine("Joshua Geary");
addCreditsLine("Juan Pablo Erices");
addCreditsLine("Jurgen De Vos");
addCreditsLine("Justin Darity");
addCreditsLine("Justin Forward");
addCreditsLine("Justin Meske");
addCreditsLine("Justin Talley");
addCreditsLine("Karen Cobb");
addCreditsLine("Karen Holland");
addCreditsLine("Kar-Hai Chu");
addCreditsLine("Kari Gardner");
addCreditsLine("Karl Heck");
addCreditsLine("Karl Seguin");
addCreditsLine("Karre Knudsen");
addCreditsLine("Keith Allen Brown");
addCreditsLine("Keith Hampe");
addCreditsLine("Keith Lehman");
addCreditsLine("Keith Lu");
addCreditsLine("Kelly Christians");
addCreditsLine("Kelvin Kim");
addCreditsLine("Ken Herritt");
addCreditsLine("Ken Holst");
addCreditsLine("Kenneth Goh");
addCreditsLine("Kenric Tam");
addCreditsLine("Kent Daniels");
addCreditsLine("Kenzo Iwanaga");
addCreditsLine("Keoni van't Groenewout");
addCreditsLine("Kevin Christian");
addCreditsLine("Kevin Fuhst");
addCreditsLine("Kevin Lee");
addCreditsLine("Kevin Middleton");
addCreditsLine("Kevin R. McGaffey");
addCreditsLine("Kevin Rank");
addCreditsLine("Kevin Tanghe");
addCreditsLine("Kibeom Song");
addCreditsLine("Kim Anderson");
addCreditsLine("Kim Dae Uk");
addCreditsLine("Kishan Shri");
addCreditsLine("Kody Dickerson");
addCreditsLine("Kohei Iwanaga");
addCreditsLine("Kolya Rice");
addCreditsLine("Kris Bugbee");
addCreditsLine("Kris Thomson");
addCreditsLine("Kristian Christensen");
addCreditsLine("Kristo Kurtén");
addCreditsLine("Kurt Sund");
addCreditsLine("Kwabena Otchere");
addCreditsLine("Kyle Doris");
addCreditsLine("Kyle Godfrey");
addCreditsLine("Kyle Job");
addCreditsLine("Kyle Leveque");
addCreditsLine("Kyle Morrison");
addCreditsLine("Lance Tegner");
addCreditsLine("Lars Jelstad");
addCreditsLine("Laura Schreiner");
addCreditsLine("Lawrence Chung");
addCreditsLine("Lawrence Jupina");
addCreditsLine("Lee Weaver");
addCreditsLine("Leif Anderson");
addCreditsLine("Leonard Pak");
addCreditsLine("Leslie Ho Bee Chew");
addCreditsLine("Liam Byrne");
addCreditsLine("Lian Bredenkamp");
addCreditsLine("Lim Eui Taek");
addCreditsLine("Liviu Stan");
addCreditsLine("Lon Chen");
addCreditsLine("Lord Olav Rekve III");
addCreditsLine("Loren Oldham");
addCreditsLine("Lorne Laliberte");
addCreditsLine("Louie Ramones");
addCreditsLine("Lucas Goodwin");
addCreditsLine("Lucas Tvrdik");
addCreditsLine("Luis Zapata");
addCreditsLine("Luiz Ricardo Malheiros");
addCreditsLine("Luke McBeath");
addCreditsLine("Manu De Gersem");
addCreditsLine("Marc Broekhoven");
addCreditsLine("Marc Bunin");
addCreditsLine("Marc Chang");
addCreditsLine("Marc Cobelens");
addCreditsLine("Marc Elvy");
addCreditsLine("Marc Rehder");
addCreditsLine("Marco Amato");
addCreditsLine("Marco Casati");
addCreditsLine("Marcus Hurst");
addCreditsLine("Marcus Miller");
addCreditsLine("Mariano Porta");
addCreditsLine("Mario Batlle");
addCreditsLine("Mario Olivier");
addCreditsLine("Maritza Kvalsvik");
addCreditsLine("Marius Andre Aasly");
addCreditsLine("Mark Brieden");
addCreditsLine("Mark Caldwell");
addCreditsLine("Mark de Jong");
addCreditsLine("Mark Dickenson");
addCreditsLine("Mark Fiore");
addCreditsLine("Mark Hephner");
addCreditsLine("Mark Siciliano");
addCreditsLine("Mark Steurer");
addCreditsLine("Mark Szabo");
addCreditsLine("Mark Yocom");
addCreditsLine("Markus Cichy");
addCreditsLine("Markus Eisenblaetter");
addCreditsLine("Markus Eskermo");
addCreditsLine("Markus Roth");
addCreditsLine("Martin Kremer");
addCreditsLine("Martin Parker");
addCreditsLine("Mat Bettinson");
addCreditsLine("Mathew Zauher");
addCreditsLine("Mathias Lindfeldt");
addCreditsLine("Mathieu Bouchard");
addCreditsLine("Matt Berkland");
addCreditsLine("Matt Brunmeier");
addCreditsLine("Matt Chandronait");
addCreditsLine("Matt Cohen");
addCreditsLine("Matt Collins");
addCreditsLine("Matt Craw");
addCreditsLine("Matt Culp");
addCreditsLine("Matt Davis");
addCreditsLine("Matt DeWald");
addCreditsLine("Matt Grange");
addCreditsLine("Matt Green");
addCreditsLine("Matt McCall");
addCreditsLine("Matt Timlin");
addCreditsLine("Matt Vilcsak");
addCreditsLine("Matt Wilson");
addCreditsLine("Matthew A. Clarke");
addCreditsLine("Matthew Frolick");
addCreditsLine("Matthew Jenkins");
addCreditsLine("Matthew Keen");
addCreditsLine("Matthew Keith");
addCreditsLine("Matthew McKeown");
addCreditsLine("Matthew Williams");
addCreditsLine("Matthias Schneidt");
addCreditsLine("Maurice Kambach");
addCreditsLine("Maurice Tan");
addCreditsLine("Mauro Artou");
addCreditsLine("Max Robins");
addCreditsLine("Melissa Webb");
addCreditsLine("Meredith Marine");
addCreditsLine("Michael A Pratt");
addCreditsLine("Michael Carroll");
addCreditsLine("Michael Dunne");
addCreditsLine("Michael Ennis");
addCreditsLine("Michael Hamlett");
addCreditsLine("Michael Jacovina");
addCreditsLine("Michael Johnston");
addCreditsLine("Michael Kenney");
addCreditsLine("Michael Parks");
addCreditsLine("Michael Strong");
addCreditsLine("Michael Tan It Han");
addCreditsLine("Michael Valera");
addCreditsLine("Michael van Huystee");
addCreditsLine("Michael Voigt");
addCreditsLine("Michael Waldvogle");
addCreditsLine("Michael Wichter");
addCreditsLine("Michael Thornton");
addCreditsLine("Mickey Borchardt");
addCreditsLine("Miguel Schneeberger");
addCreditsLine("Mika Hyvonen");
addCreditsLine("Mikael Garde Nielsen");
addCreditsLine("Mike Benton");
addCreditsLine("Mike Burton");
addCreditsLine("Mike Comroe");
addCreditsLine("Mike Cutillo");
addCreditsLine("Mike Dally");
addCreditsLine("Mike Fedorov");
addCreditsLine("Mike Hillebrecht");
addCreditsLine("Mike Large");
addCreditsLine("Mike Leeder");
addCreditsLine("Mike Mann");
addCreditsLine("Mike Plavin");
addCreditsLine("Mike Ransom");
addCreditsLine("Mike Swanson");
addCreditsLine("Mike Weiss");
addCreditsLine("Mikkel Johansen");
addCreditsLine("Ming Jack Po");
addCreditsLine("Minos Dounias");
addCreditsLine("Moonja Choi");
addCreditsLine("Morghan Laswell");
addCreditsLine("Motohiko Kimura");
addCreditsLine("Moussa Khan");
addCreditsLine("Myles Angell");
addCreditsLine("N. David Griffin");
addCreditsLine("Naoki Yokoyama");
addCreditsLine("Nate Timperley");
addCreditsLine("Nathan Clark");
addCreditsLine("Nathan Sweet");
addCreditsLine("Neal Sample");
addCreditsLine("Neale Guy");
addCreditsLine("Neil Crabaugh");
addCreditsLine("Neil Witkin");
addCreditsLine("Nelson Billedo");
addCreditsLine("Nemar Velasquez");
addCreditsLine("Niall Chadwick");
addCreditsLine("Nic Minnis");
addCreditsLine("Nicholas Chea");
addCreditsLine("Nicholas Paufler");
addCreditsLine("Nick Berthet");
addCreditsLine("Nick Bogolyubov");
addCreditsLine("Nick Carr");
addCreditsLine("Nick Goebel");
addCreditsLine("Nick Martini");
addCreditsLine("Nick Orlich");
addCreditsLine("Nick Petska");
addCreditsLine("Nick Rose");
addCreditsLine("Nick S. Pasto");
addCreditsLine("Nico Schlichting");
addCreditsLine("Nicolas Roux");
addCreditsLine("Niklas Westerlund");
addCreditsLine("Nikolai Sagun");
addCreditsLine("Octavian  Busuioc");
addCreditsLine("Ola Olsson");
addCreditsLine("Olivier Roulx");
addCreditsLine("Omar Yehia");
addCreditsLine("Or Yerushalmi");
addCreditsLine("Orlando Rojas");
addCreditsLine("Oscar Bossi");
addCreditsLine("P. Bryan Edge-Salois");
addCreditsLine("P.J. Allen");
addCreditsLine("Pamela A. Holmberg");
addCreditsLine("Pamela McClean");
addCreditsLine("Paolo Neé");
addCreditsLine("Paolo Petrini");
addCreditsLine("Pär Nordenstam");
addCreditsLine("Pascal Buettikofer");
addCreditsLine("Pascal Woudenberg");
addCreditsLine("Pat Callahan");
addCreditsLine("Pat Donovan");
addCreditsLine("Patricio Foieri");
addCreditsLine("Patrick Bryant");
addCreditsLine("Patrick Fitzsimons");
addCreditsLine("Patrick Kramer");
addCreditsLine("Patrick Peters");
addCreditsLine("Patrick Thomas");
addCreditsLine("Patrick Zerr");
addCreditsLine("Patrizia Bischof");
addCreditsLine("Paul Adriance");
addCreditsLine("Paul Barnes");
addCreditsLine("Paul Doucet");
addCreditsLine("Paul Grimes");
addCreditsLine("Paul Hormis");
addCreditsLine("Paul J. Paella");
addCreditsLine("Paul Jeacock");
addCreditsLine("Paul Magyar");
addCreditsLine("Paul McClelland");
addCreditsLine("Paul Morris");
addCreditsLine("Paul Polzer");
addCreditsLine("Paul Prestopnik");
addCreditsLine("Paul Ruhan");
addCreditsLine("Paul Tousignant");
addCreditsLine("Paul Warren");
addCreditsLine("Paul Wedgwood");
addCreditsLine("Paul Williams");
addCreditsLine("Paul Wright");
addCreditsLine("Penny Miller");
addCreditsLine("Per Kristiansen");
addCreditsLine("Per Vestersgaard-Andersen");
addCreditsLine("Pete Harris");
addCreditsLine("Peter Baker");
addCreditsLine("Peter Brindöpke");
addCreditsLine("Peter Brock Madsen");
addCreditsLine("Peter Davis");
addCreditsLine("Peter Kazmierow");
addCreditsLine("Peter Mayberry");
addCreditsLine("Peter Pistorius");
addCreditsLine("Peter Romano");
addCreditsLine("Peter Vaisvil");
addCreditsLine("Peter Wittig");
addCreditsLine("Petter Eriksson");
addCreditsLine("Petteri Taipale");
addCreditsLine("Phil & Rebecca Carey");
addCreditsLine("Phil Pappas");
addCreditsLine("Philip Charles Maslied");
addCreditsLine("Philip Schultz");
addCreditsLine("Phill Curiale");
addCreditsLine("Phillip Ervin");
addCreditsLine("Phillip Kono");
addCreditsLine("Phillip Ploesser");
addCreditsLine("Phillip Stewart");
addCreditsLine("Pöchhacker Lee");
addCreditsLine("Prasad Galpoththawela");
addCreditsLine("Radu Lucian");
addCreditsLine("Rafi Zaguri");
addCreditsLine("Ragnar Lonn");
addCreditsLine("Ramiro Salgado Echeverria");
addCreditsLine("Raphael Choo Boon Leck");
addCreditsLine("Rasmus Have");
addCreditsLine("Rene Bortko");
addCreditsLine("Rene Wesselius");
addCreditsLine("Ren-Wey Yang");
addCreditsLine("Res Ngata");
addCreditsLine("Reto Baumann");
addCreditsLine("Ric Moseley");
addCreditsLine("Richard Casto");
addCreditsLine("Richard Cole");
addCreditsLine("Richard Egglestone");
addCreditsLine("Richard Freeouf");
addCreditsLine("Richard Low");
addCreditsLine("Richard McCarthy");
addCreditsLine("Richard Shackleton");
addCreditsLine("Richard Thurlow");
addCreditsLine("Rick Buford");
addCreditsLine("Ricky Fernandez");
addCreditsLine("Rino Nielsen");
addCreditsLine("Rob Cundiff");
addCreditsLine("Rob Duffy");
addCreditsLine("Rob Jones");
addCreditsLine("Rob Rynda");
addCreditsLine("Rob Tyre");
addCreditsLine("Rob Weller");
addCreditsLine("Robert Apsel");
addCreditsLine("Robert Cass");
addCreditsLine("Robert Hinkle");
addCreditsLine("Robert Jahnel");
addCreditsLine("Robert Layser");
addCreditsLine("Robert LeBlanc");
addCreditsLine("Robert Polzer");
addCreditsLine("Robert Villasana");
addCreditsLine("Roberto Toldo");
addCreditsLine("Rocco Borg");
addCreditsLine("Rod Chrenek");
addCreditsLine("Rogelio Olguin");
addCreditsLine("Roger Sewell");
addCreditsLine("Roland Chabbey");
addCreditsLine("Ron Anshel");
addCreditsLine("Ronen Lazarovitch");
addCreditsLine("Ross A. Carlson");
addCreditsLine("Ross Carlson");
addCreditsLine("Ross Litchfield");
addCreditsLine("Roy Greenhalgh");
addCreditsLine("Rozsonits László");
addCreditsLine("Rozsonits Tibor");
addCreditsLine("Ruben Eikeland");
addCreditsLine("Ruben Pauwels");
addCreditsLine("Rune Fjeld Olsen");
addCreditsLine("Rune Håkansson");
addCreditsLine("Rune Warhuus");
addCreditsLine("Russ Davies");
addCreditsLine("Russell Mein");
addCreditsLine("Russell Thompson");
addCreditsLine("Ryan Bailey");
addCreditsLine("Ryan Counts");
addCreditsLine("Ryan Gilfillan");
addCreditsLine("Ryan Hopsecker");
addCreditsLine("Ryan Kelly");
addCreditsLine("Ryan Lee");
addCreditsLine("Ryan Schoonmaker");
addCreditsLine("Ryan Thernes");
addCreditsLine("Sam Mackrill");
addCreditsLine("Sam Tanis");
addCreditsLine("Sam Whitehead");
addCreditsLine("Samuel Heffley");
addCreditsLine("Samuel L Jones");
addCreditsLine("Sarah Johnstone");
addCreditsLine("Scott Abeyta");
addCreditsLine("Scott Allison");
addCreditsLine("Scott Bair");
addCreditsLine("Scott Dennis");
addCreditsLine("Scott Egashira");
addCreditsLine("Scott Estabrook");
addCreditsLine("Scott Jenkins");
addCreditsLine("Scott Kennedy");
addCreditsLine("Scott McCulloch");
addCreditsLine("Scott Medlin");
addCreditsLine("Scott Miller");
addCreditsLine("Scott Pearson");
addCreditsLine("Scott Stahl");
addCreditsLine("Scotty Theriot");
addCreditsLine("Sean Brezniak");
addCreditsLine("Sean Bryson");
addCreditsLine("Sean Claflin");
addCreditsLine("Sean Dawson");
addCreditsLine("Sean Fitzsimons");
addCreditsLine("Sean M. Davis");
addCreditsLine("Sean Parramore");
addCreditsLine("Sean Polzer");
addCreditsLine("Sean Stanley");
addCreditsLine("Sean Swayze");
addCreditsLine("Sean Uezu");
addCreditsLine("Sebastian Stange");
addCreditsLine("Sebastien Guillemet");
addCreditsLine("Sebastien Jesionka");
addCreditsLine("Sergey Kovrov");
addCreditsLine("Seth Buntain");
addCreditsLine("Seth Thompson");
addCreditsLine("Shae Pritchard-Martinez");
addCreditsLine("Shane Beaumont");
addCreditsLine("Shane Evans");
addCreditsLine("Shane Froebel");
addCreditsLine("Shane Taylor");
addCreditsLine("Shaun Newsome");
addCreditsLine("Shawn Christenson");
addCreditsLine("Shelby Townsend");
addCreditsLine("Si Donbavand");
addCreditsLine("Simon Gooding");
addCreditsLine("Simon Malo");
addCreditsLine("Simon Muir");
addCreditsLine("Simon Pedersen");
addCreditsLine("Sing Wu");
addCreditsLine("Sjaak Ursinus");
addCreditsLine("Skip McIlvaine");
addCreditsLine("Sohail Bhamani");
addCreditsLine("Spencer Tsai");
addCreditsLine("Stacey A Ross");
addCreditsLine("Stan C Audle");
addCreditsLine("Stan Ilin");
addCreditsLine("Stan James");
addCreditsLine("Stef Johannes Henderson");
addCreditsLine("Stefan Grufman");
addCreditsLine("Stefan Kiesel");
addCreditsLine("Stefano Petrullo");
addCreditsLine("Stefano Zanola");
addCreditsLine("Steffen Knapp");
addCreditsLine("Stephan Brezinsky");
addCreditsLine("Stephen Cimprich");
addCreditsLine("Stephen Le Petit");
addCreditsLine("Stephen Limowski");
addCreditsLine("Stephen Lynch");
addCreditsLine("Stephen Summerell");
addCreditsLine("Steve Bailey");
addCreditsLine("Steve Batham");
addCreditsLine("Steve Carrion");
addCreditsLine("Steve Gibson");
addCreditsLine("Steve Nixon");
addCreditsLine("Steve Pompel");
addCreditsLine("Steve Saulle");
addCreditsLine("Steve Smith");
addCreditsLine("Steve Stryd");
addCreditsLine("Steve Tory");
addCreditsLine("Steven E. Adams");
addCreditsLine("Steven Grossman");
addCreditsLine("Steven Kats");
addCreditsLine("Steven Knox");
addCreditsLine("Steven Kusewicz");
addCreditsLine("Stewart Laufer");
addCreditsLine("Stewart Tosh");
addCreditsLine("Stuart Ross Robertson");
addCreditsLine("T.J. Allard");
addCreditsLine("Takafumi Kobayashi");
addCreditsLine("Takashi Morikawa");
addCreditsLine("Tal Muskal");
addCreditsLine("Tal Nelson");
addCreditsLine("Tan Peng Koon");
addCreditsLine("Tanner Burgess");
addCreditsLine("Taylor Stewart");
addCreditsLine("Taylor Suchan");
addCreditsLine("Teck Wong");
addCreditsLine("Terje Alexander Barth");
addCreditsLine("Tero Heija");
addCreditsLine("Theresa Petersen");
addCreditsLine("Thomas Dönnecke");
addCreditsLine("Thomas From");
addCreditsLine("Thomas Goemaere");
addCreditsLine("Thomas Hardy");
addCreditsLine("Thomas Kumpik, Jr.");
addCreditsLine("Thomas Prinz");
addCreditsLine("Thomas R. Bissell III");
addCreditsLine("Thomas Ribbeck");
addCreditsLine("Tiffany Diaz");
addCreditsLine("Tim Engelman");
addCreditsLine("Tim Hammock");
addCreditsLine("Tim Kautz");
addCreditsLine("Tim ONeil");
addCreditsLine("Tim Rider");
addCreditsLine("Tim Smith");
addCreditsLine("Tim Thompson");
addCreditsLine("Tim Yeung");
addCreditsLine("Timen Wuestman");
addCreditsLine("Timothy C. Stanton");
addCreditsLine("Timothy Lewis");
addCreditsLine("Todd Northcutt");
addCreditsLine("Todd Sjoblom");
addCreditsLine("Tom Beijar Johansson");
addCreditsLine("Tom Carel");
addCreditsLine("Tom Ellis");
addCreditsLine("Tom Fulton");
addCreditsLine("Tom Gordon");
addCreditsLine("Tom Roger Tranø");
addCreditsLine("Tom Szabo");
addCreditsLine("Tom Vogt");
addCreditsLine("Tomi Partanen");
addCreditsLine("Toni Ahonen");
addCreditsLine("Tony Caskanette");
addCreditsLine("Torbjørn Østlund");
addCreditsLine("Travis Ramme");
addCreditsLine("Trent Donelson");
addCreditsLine("Trevor Lanz");
addCreditsLine("Trevor McGuire");
addCreditsLine("Troy H. Benson");
addCreditsLine("Troy Lee");
addCreditsLine("Tyler Endicott");
addCreditsLine("Tyler Frans");
addCreditsLine("Tyler Jacobson");
addCreditsLine("Tyler Jensen");
addCreditsLine("Tyler Lott");
addCreditsLine("Uli Muller");
addCreditsLine("Verner Fortelius");
addCreditsLine("Vic Stelter");
addCreditsLine("Vidar Almås Pettersen");
addCreditsLine("Ville Halonen");
addCreditsLine("Vincent Cunniffe");
addCreditsLine("Vitor Coelho");
addCreditsLine("Wai wong");
addCreditsLine("Wasif Azmat");
addCreditsLine("Wayne Opai");
addCreditsLine("Wayne Tory");
addCreditsLine("Wayne Wallace");
addCreditsLine("Werner Pötzelberger");
addCreditsLine("Wes Sanders");
addCreditsLine("Will Belknap");
addCreditsLine("Will Erickson");
addCreditsLine("Will Preisch");
addCreditsLine("Willem Bison");
addCreditsLine("William Everett");
addCreditsLine("William Goldberg");
addCreditsLine("William Helm");
addCreditsLine("William Houston");
addCreditsLine("William Klimke");
addCreditsLine("William Knop");
addCreditsLine("William Moss");
addCreditsLine("William Prideaux-Brune");
addCreditsLine("William Sherriff");
addCreditsLine("Wilson Bilkovich");
addCreditsLine("Wing Hon Lai");
addCreditsLine("Wu Yiheng");
addCreditsLine("Yanai Sachs");
addCreditsLine("YeongJin Bae");
addCreditsLine("Yongchan Jee");
addCreditsLine("Yves Peckstadt");
addCreditsLine("Zach McCuin");
addCreditsLine("Zachary Charles ");
addCreditsLine("Zachary Denholm");
addCreditsLine("Zion Mizrahi");
addCreditsLine("Zsolt Vincze");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Operation Big Booze<spop><spop>");
addCreditsLine("Phil \"Vlad\" Pappas");
addCreditsLine("Greg \"Satan\" Romaszka");
addCreditsLine("Steve \"Cpt.Wussie!!!\" Snow");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("<just:center><bitmap:twb/twb_lineup><sbreak>");
addCreditsLine("<spush><font:Univers condensed:26><spush><color:18A27B>So Long, and Thanks For All The Fish.<spop><spop>");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:c0c0c0>Tribes2 Development Team<spop><spop>", true);
