//-----------------------------------------------------------------------------
// Liquid Texture Lists
//
new LiquidProfile(water)
{
   liquidType = "water";
   viscosity = "6";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "liquidTiles/islandWater01.png";
   surfaceTex1 = "liquidTiles/islandWater02.png";
   surfaceTex2 = "liquidTiles/islandWater03.png";
   surfaceTex3 = "liquidTiles/islandWater04.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "2";
   effectTex0 = "liquidTiles/modulation03.png";
   effectTex1 = "liquidTiles/modulation04.png";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "2";
   modulatorTex0 = "liquidTiles/modulation03.png";
   modulatorTex1 = "liquidTiles/modulation04.png";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".75";
   surfacePattern = "serpentine";
   surfaceAngle = "30";
   surfaceScale = ".05 .05";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".1 .1";
   modulatorPattern = "serpentine";
   modulatorAngle = "-30";
   modulatorScale = ".07 -.07";
};

new LiquidProfile(oceanWater)
{
   liquidType = "oceanWater";
   viscosity = "6";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "liquidTiles/islandWater01.png";
   surfaceTex1 = "liquidTiles/islandWater02.png";
   surfaceTex2 = "liquidTiles/islandWater03.png";
   surfaceTex3 = "liquidTiles/islandWater04.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "2";
   effectTex0 = "liquidTiles/modulation03.png";
   effectTex1 = "liquidTiles/modulation04.png";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "2";
   modulatorTex0 = "liquidTiles/modulation03.png";
   modulatorTex1 = "liquidTiles/modulation04.png";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".75";
   surfacePattern = "serpentine";
   surfaceAngle = "30";
   surfaceScale = ".05 .05";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".1 .1";
   modulatorPattern = "serpentine";
   modulatorAngle = "-30";
   modulatorScale = ".07 -.07";
};

new LiquidProfile(riverWater)
{
   liquidType = "riverWater";
   viscosity = "6";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "liquidTiles/lushWater01.png";
   surfaceTex1 = "liquidTiles/lushWater02.png";
   surfaceTex2 = "liquidTiles/lushWater03.png";
   surfaceTex3 = "liquidTiles/lushWater04.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "2";
   effectTex0 = "liquidTiles/modulation03.png";
   effectTex1 = "liquidTiles/modulation04.png";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "2";
   modulatorTex0 = "liquidTiles/modulation03.png";
   modulatorTex1 = "liquidTiles/modulation04.png";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".5";
   surfacePattern = "serpentine";
   surfaceAngle = "30";
   surfaceScale = ".05 .05";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".1 .1";
   modulatorPattern = "serpentine";
   modulatorAngle = "-30";
   modulatorScale = ".07 -.07";
};

new LiquidProfile(stagnantWater)
{
   liquidType = "stagnantWater";
   viscosity = "6";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "liquidTiles/lushWater01_algae.png";
   surfaceTex1 = "liquidTiles/lushWater02_algae.png";
   surfaceTex2 = "liquidTiles/lushWater03_algae.png";
   surfaceTex3 = "liquidTiles/lushWater04_algae.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "2";
   effectTex0 = "liquidTiles/modulation03.png";
   effectTex1 = "liquidTiles/modulation04.png";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "2";
   modulatorTex0 = "liquidTiles/modulation03.png";
   modulatorTex1 = "liquidTiles/modulation04.png";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".25";
   surfacePattern = "circular";
   surfaceAngle = "30";
   surfaceScale = ".05 .05";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".1 .1";
   modulatorPattern = "serpentine";
   modulatorAngle = "-30";
   modulatorScale = ".07 -.07";
};

new LiquidProfile(lava)
{
   liquidType = "lava";
   viscosity = "15";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "terrainTiles/lavarockhot1.png";
   surfaceTex1 = "terrainTiles/lavarockhot2.png";
   surfaceTex2 = "terrainTiles/lavarockhot3.png";
   surfaceTex3 = "terrainTiles/lavarockhot4.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "0";
   effectTex0 = "";
   effectTex1 = "";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "0";
   modulatorTex0 = "";
   modulatorTex1 = "";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".15";
   surfacePattern = "circular";
   surfaceAngle = "30";
   surfaceScale = ".05 .05";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".1 .1";
   modulatorPattern = "none";
   modulatorAngle = "0";
   modulatorScale = "0 0";
};

new LiquidProfile(hotLava)
{
   liquidType = "hotLava";
   viscosity = "15";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "terrainTiles/lavarockhot1.png";
   surfaceTex1 = "terrainTiles/lavarockhot2.png";
   surfaceTex2 = "terrainTiles/lavarockhot3.png";
   surfaceTex3 = "terrainTiles/lavarockhot4.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "0";
   effectTex0 = "";
   effectTex1 = "";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "0";
   modulatorTex0 = "";
   modulatorTex1 = "";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".15";
   surfacePattern = "circular";
   surfaceAngle = "30";
   surfaceScale = ".05 .05";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".1 .1";
   modulatorPattern = "none";
   modulatorAngle = "0";
   modulatorScale = "0 0";
};

new LiquidProfile(crustyLava)
{
   liquidType = "lava";
   viscosity = "15";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "terrainTiles/muddyash1.png";
   surfaceTex1 = "terrainTiles/muddyash2.png";
   surfaceTex2 = "terrainTiles/muddyash3.png";
   surfaceTex3 = "terrainTiles/muddyash4.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "0";
   effectTex0 = "";
   effectTex1 = "";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "0";
   modulatorTex0 = "";
   modulatorTex1 = "";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".05";
   surfacePattern = "circular";
   surfaceAngle = "30";
   surfaceScale = ".05 .05";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".02 .02";
   modulatorPattern = "none";
   modulatorAngle = "0";
   modulatorScale = "0 0";
};

new LiquidProfile(quicksand)
{
   liquidType = "quicksand";
   viscosity = "15";
   density = "1";
   submergeColor = 2/10 @ " " @ 6/10 @ " " @ 6/10 @ " " @ 3/10;
   surfaceTextures = "4";
   surfaceTex0 = "terrainTiles/mossDirt1.png";
   surfaceTex1 = "terrainTiles/mossDirt2.png";
   surfaceTex2 = "terrainTiles/mossDirt3.png";
   surfaceTex3 = "terrainTiles/mossDirt4.png";
   surfaceTex4 = "";
   surfaceTex5 = "";
   surfaceTex6 = "";
   surfaceTex7 = "";
   effectTextures = "0";
   effectTex0 = "";
   effectTex1 = "";
   effectTex2 = "";
   effectTex3 = "";
   effectTex4 = "";
   effectTex5 = "";
   effectTex6 = "";
   effectTex7 = "";
   modulatorTextures = "0";
   modulatorTex0 = "";
   modulatorTex1 = "";
   modulatorTex2 = "";
   modulatorTex3 = "";
   waveAmplitude = ".025";
   surfacePattern = "circular";
   surfaceAngle = "30";
   surfaceScale = ".02 .02";
   effectPattern = "circular";
   effectAngle = "-60";
   effectScale = ".01 .01";
   modulatorPattern = "none";
   modulatorAngle = "0";
   modulatorScale = "0 0";
};
