//------------------------------------------------------------------------------
//
// voiceBinds.cs
//
//------------------------------------------------------------------------------

startChatMenu( "G Global" );
	startChatMenu( "A Animations" );
		addChat( "A Move", 'ChatAnimAnnoyed' );
		addChat( "G I'm the greatest", 'ChatAnimGetSome' );
		addChat( "D Woohoo", 'ChatAnimDance' );
		addChat( "S I'm on it", 'ChatAnimSalute' );
		addChat( "W Hi", 'ChatAnimWave' );
		addChat( "Z Take that", 'ChatAnimSpec1' );
		addChat( "X Too bad", 'ChatAnimSpec2' );
		addChat( "C Awesome", 'ChatAnimSpec3' );
	endChatMenu();
   startChatMenu( "C Compliment" );
      addChat( "A Awesome!", 'ChatAwesome' );
      addChat( "G Good game.", 'ChatGoodGame' );
      addChat( "N Nice move!", 'ChatNice' );
      addChat( "R You rock!", 'ChatYouRock' );
      addChat( "S Great shot!", 'ChatGreatShot' );
   endChatMenu();
   startChatMenu( "R Respond" );
      addChat( "A Anytime", 'ChatAnyTime' );
      addChat( "D Don't know", 'ChatDontKnow' );
      addChat( "T Thanks", 'ChatThanks' );
      addChat( "W Wait", 'ChatWait' );
   endChatMenu();
   startChatMenu( "T Taunt" );
      addChat( "A Aww...", 'ChatAww' );
      addChat( "B Best you can do?", 'ChatObnoxious' );
      addChat( "G I am the greatest!", 'ChatBrag' );
      addChat( "T THAT was graceful!", 'ChatSarcasm' );
      addChat( "W When will you learn?", 'ChatLearn' );
   endChatMenu();
   addChat( "Y Yes", 'ChatGlobalYes' );
   addChat( "N No", 'ChatGlobalNo' );
   addChat( "H Hi", 'ChatHi' );
   addChat( "B Bye", 'ChatBye' );
   addChat( "O Oops.", 'ChatOops' );
   addChat( "Q Quiet!", 'ChatQuiet' );
   addChat( "S Shazbot!", 'ChatShazbot' );
   addChat( "W Woohoo!", 'ChatCheer' );
endChatMenu();

startChatMenu( "A Attack" );
   addChat( "A Attack!", 'ChatCmdAttack' );
   addChat( "B Base", 'ChatCmdAttackBase' );
   addChat( "C Chase", 'ChatCmdAttackChase' );
   addChat( "D Disrupt", 'ChatCmdAttackDistract' );
   addChat( "F Flag", 'ChatCmdAttackFlag' );
   addChat( "G Generator", 'ChatCmdAttackGenerator' );
   addChat( "O Objective", 'ChatCmdAttackObjective' );
   addChat( "R Reinforce", 'ChatCmdAttackReinforce' );
   addChat( "S Sensors", 'ChatCmdAttackSensors' );
   addChat( "T Turrets", 'ChatCmdAttackTurrets' );
   addChat( "V Vehicle", 'ChatCmdAttackVehicle' );
   addChat( "W Wait", 'ChatCmdAttackWait' );
endChatMenu();

startChatMenu( "D Defend" );
   addChat( "B Base", 'ChatCmdDefendBase' );
   addChat( "C Flag carrier", 'ChatCmdDefendCarrier' );
	addChat( "E Entrances", 'ChatCmdDefendEntrances' );
   addChat( "F Flag", 'ChatCmdDefendFlag' );
   addChat( "G Generator", 'ChatCmdDefendGenerator' );
   addChat( "M Me", 'ChatCmdDefendMe' );
   addChat( "N Nexus", 'ChatCmdDefendNexus' );
   addChat( "O Objective", 'ChatCmdDefendObjective' );
   addChat( "R Reinforce", 'ChatCmdDefendReinforce' );
   addChat( "S Sensors", 'ChatCmdDefendSensors' );
   addChat( "T Turrets", 'ChatCmdDefendTurrets' );
   addChat( "V Vehicle", 'ChatCmdDefendVehicle' );
endChatMenu();

startChatMenu( "R Repair" );
   addChat( "B Base", 'ChatRepairBase' );
   addChat( "G Generator", 'ChatRepairGenerator' );
   addChat( "M Me", 'ChatRepairMe' );
   addChat( "S Sensors", 'ChatRepairSensors' );
   addChat( "T Turrets", 'ChatRepairTurrets' );
   addChat( "V Vehicle bay", 'ChatRepairVehicle' );
endChatMenu();

startChatMenu( "B Base" );
   addChat( "C Clear", 'ChatBaseClear' );
   addChat( "E Enemy in base", 'ChatEnemyInBase' );
   addChat( "R Retake", 'ChatCmdRetakeBase' );
   addChat( "S Secure", 'ChatBaseSecure' );
   addChat( "T Taken", 'ChatBaseTaken' );
endChatMenu();

startChatMenu( "C Command" );
   addChat( "A Acknowledged", 'ChatCmdAcknowledged' );
   addChat( "C Completed", 'ChatCmdCompleted' );
   addChat( "D Declined", 'ChatCmdDeclined' );
	addChat( "W Assignment?", 'ChatCmdWhat' );
endChatMenu();

startChatMenu( "E Enemy" );
   addChat( "B Base disabled", 'ChatEnemyBaseDisabled' );
   addChat( "D Disarray", 'ChatEnemyDisarray' );
   addChat( "G Generator destroyed", 'ChatEnemyGeneratorDestroyed' );
   addChat( "R Remotes destroyed", 'ChatEnemyRemotesDestroyed' );
   addChat( "S Sensors destroyed", 'ChatEnemySensorsDestroyed' );
   addChat( "T Turrets destroyed", 'ChatEnemyTurretsDestroyed' );
   addChat( "V Vehicle bay destroyed", 'ChatEnemyVehicleDestroyed' );
endChatMenu();

startChatMenu( "F Flag" );
   addChat( "D Defend", 'ChatCmdDefendFlag' );
   addChat( "F I have the flag", 'ChatFlagGotIt' );
   addChat( "G Give me", 'ChatCmdGiveMeFlag' );
   addChat( "R Retrieve", 'ChatCmdReturnFlag' );
   addChat( "S Secure", 'ChatFlagSecure' );
   addChat( "T Take", 'ChatCmdTakeFlag' );
   addChat( "O Give me your flags", 'ChatCmdHunterGiveFlags' );
   addChat( "P Take my flags", 'ChatCmdHunterTakeFlags' );
endChatMenu();

startChatMenu( "N Need" );
   addChat( "B Bombardier", 'ChatNeedBombardier' );
   addChat( "C Cover", 'ChatNeedCover' );
   addChat( "D Driver", 'ChatNeedDriver' );
   addChat( "E Escort", 'ChatNeedEscort' );
   addChat( "G Gunship ready", 'ChatNeedPassengers' );
   addChat( "H Hold vehicle", 'ChatNeedHold' );
   addChat( "P Pilot", 'ChatNeedPilot' );
   addChat( "R Ride", 'ChatNeedRide' );
   addChat( "S Support", 'ChatNeedSupport' );
   addChat( "T Tailgunner", 'ChatNeedTailgunner' );
   addChat( "W Where to?", 'ChatNeedDestination' );
endChatMenu();

startChatMenu( "S Self" );
   startChatMenu( "A Attack" );
      addChat( "A Attack", 'ChatSelfAttack' );
      addChat( "B Base", 'ChatSelfAttackBase' );
      addChat( "F Flag", 'ChatSelfAttackFlag' );
      addChat( "G Generator", 'ChatSelfAttackGenerator' );
      addChat( "S Sensors", 'ChatSelfAttackSensors' );
      addChat( "T Turrets", 'ChatSelfAttackTurrets' );
      addChat( "V Vehicle bay", 'ChatSelfAttackVehicle' );
   endChatMenu();
   startChatMenu( "D Defend" );
      addChat( "B Base", 'ChatSelfDefendBase' );
      addChat( "D Defend", 'ChatSelfDefend' );
      addChat( "F Flag", 'ChatSelfDefendFlag' );
      addChat( "G Generator", 'ChatSelfDefendGenerator' );
      addChat( "N Nexus", 'ChatSelfDefendNexus' );
      addChat( "S Sensors", 'ChatSelfDefendSensors' );
      addChat( "T Turrets", 'ChatSelfDefendTurrets' );
      addChat( "V Vehicle bay", 'ChatSelfDefendVehicle' );
   endChatMenu();
   startChatMenu( "R Repair" );
      addChat( "B Base", 'ChatSelfRepairBase' );
      addChat( "E Equipment", 'ChatSelfRepairEquipment' );
      addChat( "G Generator", 'ChatSelfRepairGenerator' );
      addChat( "R Repair", 'ChatSelfRepair' );
      addChat( "S Sensors", 'ChatSelfRepairSensors' );
      addChat( "T Turrets", 'ChatSelfRepairTurrets' );
      addChat( "V Vehicle bay", 'ChatSelfRepairVehicle' );
   endChatMenu();
   startChatMenu( "T Task" );
      addChat( "C Cover", 'ChatTaskCover' );
      addChat( "D Setup defenses", 'ChatTaskSetupD' );
      addChat( "O On it", 'ChatTaskOnIt' );
      addChat( "R Deploy remotes", 'ChatTaskSetupRemote' );
      addChat( "S Deploy sensors", 'ChatTaskSetupSensors' );
      addChat( "T Deploy turrets", 'ChatTaskSetupTurrets' );
      addChat( "V Vehicle", 'ChatTaskVehicle' );
   endChatMenu();
endChatMenu();

startChatMenu( "T Target" );
   addChat( "A Acquired", 'ChatTargetAcquired' );
   addChat( "B Base", 'ChatCmdTargetBase' );
   addChat( "D Destroyed", 'ChatTargetDestroyed' );
   addChat( "F Flag", 'ChatCmdTargetFlag' );
   addChat( "M Fire on my target", 'ChatTargetFire' );
   addChat( "N Need", 'ChatTargetNeed' );
   addChat( "S Sensors", 'ChatCmdTargetSensors' );
   addChat( "T Turret", 'ChatCmdTargetTurret' );
   addChat( "W Wait", 'ChatCmdTargetWait' );
endChatMenu();

startChatMenu( "W Warning" );
   addChat( "B Bomber", 'ChatWarnBomber' );
   addChat( "E Enemies", 'ChatWarnEnemies' );
   addChat( "V Vehicles", 'ChatWarnVehicles' );
   addChat( "W Watch your shooting", 'ChatWarnShoot' );
endChatMenu();

startChatMenu( "V Very Quick" );
   addChat( "Y Yes", 'ChatTeamYes' );
   addChat( "N No", 'ChatTeamNo' );
   addChat( "A Anytime", 'ChatWelcome' );
   addChat( "B Base secure?", 'ChatIsBaseSecure' );
   addChat( "C Cease fire", 'ChatCeaseFire' );
   addChat( "D Don't know", 'ChatDunno' );
   addChat( "H HELP!", 'ChatHelp' );
   addChat( "M Move", 'ChatMove' );
   addChat( "S Sorry", 'ChatSorry' );
   addChat( "T Thanks", 'ChatTeamThanks' );
   addChat( "W Wait", 'ChatTeamWait' );
endChatMenu();
